[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1


[fa]
languageName = "پارسی"
languagedirection = "rtl"
title = "آفش غلامی"
weight = 1


[ar]
languageName = "العربية"
languagedirection = "rtl"
title = "آفش غلامی"
weight = 1