# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/afash7"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Telegram"
name = "Telegram"
url = "https://t.me/geektoria"

[social.params]
icon = "telegram.svg"
